Документ №1184429129 от 2022-01-18 Санников К.А.
saby/ui pull request #5009
Opened 2022-01-26 13:14 UTC by github-auto-merge

https://online.sbis.ru/doc/a488029e-7214-45ab-8917-9eb60dcc7105  BLOCKER Ошибка в тестах<br>rc_saby_page_22.1000/(int-chrome) 22.1000 saby-page react #6 test - test_05_middle_up [Jenkins] (sbis.ru)

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +   originalIntersectionObserver = IntersectionObserver;
метод может быть вызван более одного раза и тогда оверрайд будет наслаиваться на оверрайд

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +    if (typeof IntersectionObserver === 'undefined') {
если полифиллы то они не будут заменены а надо чтобы при них тоже работало

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +    if (typeof IntersectionObserver === 'undefined') {
мы решили это позже сделать? есть задача?

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +   overrideObserver.prototype = originalIntersectionObserver.prototype;
как то все сложно. мне казалось достаточно пару методов переопределить

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +initIntersectionObserver()
почему это вызывается тут если еще вызывается в createControl

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/ResizeObserver.ts
> +                const control = entries[0].target.querySelector('[name="$$wasaby$async$loading"]')?.controlNodes[0].control;
$$wasaby$async$loading - что это? откуда это? кто ставит? не подменится ли там правильный нэйм? зачем звать 2 раза querySelector если можно 1 раз?

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/ResizeObserver.ts
> +                control._$observerCallback = _observerCallback;
плохо понимаю концепцию этого решения

2022-01-26 15:48 UTC, nekqy commented on UIReact/UICore/_base/IntersectionObserver.ts
> +      return new originalIntersectionObserver.prototype.constructor(overrideCallback, options);
тут начинает подсовываться некий колбек. что это нам дает? как тут будет собираться и останавливаться работать обсервера?

2022-01-26 15:53 UTC, trogwarrus commented on UIReact/UICore/_base/IntersectionObserver.ts
> +    if (typeof IntersectionObserver === 'undefined') {
мы решили сначала решить текущую проблему, а уже потом переносить полифил из контролов

2022-01-26 16:02 UTC, trogwarrus commented on UIReact/UICore/_base/IntersectionObserver.ts
> +   overrideObserver.prototype = originalIntersectionObserver.prototype;
типы обсерверов хитро определены, их прототипы в лоб не получится переопределить.
например, ResizeObserver описан так:
```
interface ResizeObserver {
    disconnect(): void;
    observe(target: Element, options?: ResizeObserverOptions): void;
    unobserve(target: Element): void;
}

declare var ResizeObserver: {
    prototype: ResizeObserver;
    new(callback: ResizeObserverCallback): ResizeObserver;
};
```
Если попробовать переопределить прототип, то в рантайме будет ошибка, т.к. будет ситуация что мы переопределяем прототип у var ResizeObserver, которого по сути нет.
Если переопределить прототип внутри var ResizeObserver, то при вызове new будет использоваться нативный new из var ResizeObserver.
Поэтому надо подменить нативную реализацию на нашу, которая оборачивает нативную.

И уже в нашей реализации мы будем перегружать нужный конструктор, который будет вызываться при new ResizeObserver()

2022-01-26 16:07 UTC, trogwarrus commented on UIReact/UICore/_base/ResizeObserver.ts
> +                const control = entries[0].target.querySelector('[name="$$wasaby$async$loading"]')?.controlNodes[0].control;
$$wasaby$async$loading  это имя контрола который мы рисуем для асинхронных контролов
можно посмотреть  в `UIReact\UICore\_base\Control\LoaderIndicator`

Тут идея в том, что если внутри обозреваемого контейнера строится что-то асинхронное (например по событию), то нужно дождаться его рендера и только после этого вызывать колбэк обсервера, чтобы считать реальные изменения высоты, а не сначала пустоту, а потом реальную.

2022-01-26 16:09 UTC, trogwarrus commented on UIReact/UICore/_base/ResizeObserver.ts
> +                control._$observerCallback = _observerCallback;
как выше писал, надо сохранить колбэк обсервера и выстрелить его из хука контрола, после рендера.
сам сохраненный колбэк надо удалить, чтобы не было ложных вызовов.

2022-01-26 16:11 UTC, trogwarrus commented on UIReact/UICore/_base/IntersectionObserver.ts
> +      return new originalIntersectionObserver.prototype.constructor(overrideCallback, options);
это переопределение на будущее, чтобы у нас был рычаг с помощью которого мы сможем управлять IntersectionObserver'ом
сейчас менять логику вызова колбэка IntersectionObserver'а нет смысла, т.к. во всем местах она зависит от ResizeObserver'а

2022-01-26 16:25 UTC, trogwarrus commented on UIReact/UICore/_base/IntersectionObserver.ts
> +   originalIntersectionObserver = IntersectionObserver;
поправил

2022-01-26 16:25 UTC, trogwarrus commented on UIReact/UICore/_base/IntersectionObserver.ts
> +initIntersectionObserver()
поправил

2022-01-27 12:32 UTC, SowingSadness requested changes

2022-01-27 12:32 UTC, SowingSadness commented on UIReact/UICore/_base/Control/WasabyHooksCaller.ts
> +    addObserverCallbackToQueue(instance: Control): void {
не должно быть публичным методом

2022-01-27 12:32 UTC, SowingSadness commented on UIReact/UICore/_base/Control/WasabyHooksCaller.ts
> +        if (instance._$observerCallback) {
Инвертировать условие и сделать ранний выход

2022-01-27 14:09 UTC, merged